enum SocketMessageType {
  LOGIN_CURRENT = 'USER_LOGIN',
  LOGOUT_CURRENT = 'USER_LOGOUT',
  LOGIN_EXTERNAL = 'USER_EXTERNAL_LOGIN',
  LOGOUT_EXTERNAL = 'USER_EXTERNAL_LOGOUT',
  ACTIVE_USERS = 'USER_ACTIVE',
  INACTIVE_USERS = 'USER_INACTIVE',
  MSG_SEND = 'MSG_SEND',
  MSG_FROM_USER = 'MSG_FROM_USER',
  MSG_DELIVERED = 'MSG_DELIVER',
  MSG_READ = 'MSG_READ',
  MSG_DELETE = 'MSG_DELETE',
  MSG_EDIT = 'MSG_EDIT',
  ERROR = 'ERROR',
}

export default SocketMessageType;
